pipeline {
    agent any

    environment {
        DIRECTORY_PATH = 'C:\Users\20467\OneDrive\Desktop\git' 
        TESTING_ENVIRONMENT = 'testing-environment' 
        PRODUCTION_ENVIRONMENT = 'ZongyangHuang' 
    }

    stages {
        stage('Build') {
            steps {
                echo "fetch the source code from the directory path specified by the environment variable: ${env.DIRECTORY_PATH}"
                echo "compile the code and generate any necessary artifacts"
            }
        }
        stage('Test') {
            steps {
                echo 'unit tests'
                echo 'integration tests'
            }
        }
        stage('Code Quality Check') {
            steps {
                echo 'check the quality of the code'
            }
        }
        stage('Deploy') {
            steps {
                echo "deploy the application to a testing environment specified by the environment variable: ${env.TESTING_ENVIRONMENT}"
            }
        }
        stage('Approval') {
            steps {
                script {
                    input message: 'Do you want to deploy to production?'
                    sleep(time: 10, unit: 'SECONDS')
                }
            }
        }
        stage('Deploy to Production') {
            steps {
                echo "deploy the code to the production environment using the environment variable: ${env.PRODUCTION_ENVIRONMENT}"
            }
        }
    }
}
